# Generated by Django 4.2.6 on 2023-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_withunit_farm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithUnit',
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_unit',
            field=models.IntegerField(choices=[('ac', 'Acre'), ('ha', 'Hectare')], verbose_name='Farm_Unit'),
        ),
    ]
