# Generated by Django 4.2.6 on 2023-10-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_delete_withunit_alter_farm_farm_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
    ]
