# Generated by Django 4.2.6 on 2023-10-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_remove_farm_farmer_alter_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer', verbose_name='Farmer'),
        ),
    ]
