# Generated by Django 4.2.6 on 2023-10-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_alter_farm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landUnitName', models.CharField(max_length=50)),
                ('landUnitAbbreviation', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='farm_size',
            new_name='farmSize',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_unit',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='name',
        ),
        migrations.AddField(
            model_name='farm',
            name='farmName',
            field=models.CharField(default='Arnold farm', max_length=50, verbose_name=' Farm Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='farmUnit',
            field=models.IntegerField(choices=[('Acres', 'Acres'), ('Hectares', 'Hectares')], default='2', verbose_name='Farm_Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmerName',
            field=models.CharField(default='Arnold Omondi', max_length=50, verbose_name='Farmer Name'),
            preserve_default=False,
        ),
    ]
