# Generated by Django 4.2.6 on 2023-10-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_landunit_rename_farm_size_farm_farmsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmUnit',
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='landUnit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.landunit', verbose_name='Land Unit of Measure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmSize',
            field=models.CharField(max_length=50, verbose_name='Farm Size'),
        ),
    ]
