# Generated by Django 4.2.6 on 2023-10-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Input Category',
                'verbose_name_plural': 'Input Categories',
            },
        ),
        migrations.CreateModel(
            name='InputSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Supplier')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='InputSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitySupplied', models.CharField(max_length=50, verbose_name='Quantity Supplied')),
                ('dispatchDate', models.DateField(verbose_name='Dispatch Date')),
                ('inputCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.inputcategory', verbose_name='Category')),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.inputsupplier', verbose_name='Supplier')),
            ],
        ),
    ]
