# Generated by Django 4.2.6 on 2023-10-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputsupply',
            options={'verbose_name': 'Input Supply', 'verbose_name_plural': 'Input Supplies'},
        ),
    ]
