# Generated by Django 4.2.6 on 2023-10-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_alter_inputsupply_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representativeNationalId', models.CharField(max_length=50, verbose_name='Represntative National ID')),
                ('dispatchedQuantity', models.CharField(max_length=50, verbose_name='Dispatched Quantity')),
                ('inputSupplyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.inputsupply', verbose_name='Input Supply')),
            ],
        ),
    ]
