# Generated by Django 4.2.6 on 2023-10-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_alter_farm_name'),
        ('input', '0003_inputdistribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputdistribution',
            options={'verbose_name': 'Input Distribution'},
        ),
        migrations.AddField(
            model_name='inputdistribution',
            name='farmerId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='farmer.farmer', verbose_name='Farmer'),
        ),
    ]
