# Generated by Django 4.2.6 on 2023-10-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_alter_inputdistribution_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputcategory',
            old_name='name',
            new_name='inputCategoryName',
        ),
        migrations.RenameField(
            model_name='inputsupplier',
            old_name='name',
            new_name='inputSupplierName',
        ),
    ]
