# Generated by Django 4.2.6 on 2023-10-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_rename_name_inputcategory_inputcategoryname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdistribution',
            old_name='farmerId',
            new_name='farmer',
        ),
        migrations.RenameField(
            model_name='inputdistribution',
            old_name='inputSupplyId',
            new_name='inputSupply',
        ),
        migrations.RenameField(
            model_name='inputsupply',
            old_name='supplierId',
            new_name='supplier',
        ),
    ]
