# Generated by Django 4.2.6 on 2023-10-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.cropcategory')),
            ],
        ),
    ]
