# Generated by Django 4.2.6 on 2023-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_alter_cropcategory_options_alter_crop_categoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingcycle',
            name='expectedHarvestAmount',
            field=models.CharField(choices=[('Kgs', 'Kilograms'), ('t', 'Tonnes')], max_length=50, verbose_name='Expected Harvest Date'),
        ),
    ]
