# Generated by Django 4.2.6 on 2023-10-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_alter_plantingcycle_expectedharvestamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingcycle',
            name='cropId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='plantingcycle',
            name='expectedHarvestAmount',
            field=models.CharField(max_length=50, verbose_name='Expected Harvest Amount'),
        ),
    ]
