# Generated by Django 4.2.6 on 2023-10-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_alter_plantingcycle_cropid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropcategory',
            old_name='name',
            new_name='cropCategoryName',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.AddField(
            model_name='crop',
            name='cropName',
            field=models.CharField(default='maize', max_length=50, verbose_name='Crop Name'),
            preserve_default=False,
        ),
    ]
