# Generated by Django 4.2.6 on 2023-10-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_remove_plantingcycle_id_plantingcycle_farmid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingcycle',
            name='cropId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop', verbose_name='Crop'),
        ),
    ]
