# Generated by Django 4.2.6 on 2023-10-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.county')),
            ],
        ),
    ]
