# Generated by Django 4.2.6 on 2023-10-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'verbose_name': 'Sub-County', 'verbose_name_plural': 'Sub-Counties'},
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('subCounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Village')),
                ('communityArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.communityarea')),
            ],
        ),
        migrations.AddField(
            model_name='communityarea',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.ward'),
        ),
    ]
