# Generated by Django 4.2.6 on 2023-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_communityarea_alter_subcounty_options_ward_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
