# Generated by Django 4.2.6 on 2023-10-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0003_alter_village_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityarea',
            old_name='name',
            new_name='communityAreaName',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='name',
            new_name='countyName',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='name',
            new_name='subCountyName',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='name',
            new_name='villageName',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='name',
            new_name='wardName',
        ),
    ]
